### ISSUE TITLE
익헨 다운로드에서

### ISSUE THREAD

**Issue by whatohyou** [gisellevonbingen/DoujinshiDownloader#1]
한장씩 받는 것 말고 리셈플된 아카이브를 다운로드하도록 설정할 수는 없나요?

**Comment by gisellevonbingen** [comment]
좋은 생각이네요 실제로 저도 저장할때는 압축파일로 저장하거든요.
그러면 [설정] - [다운로드 설정] 쪽에 '다운로드 완료 시 압축' 이라는 설정을 추가하는쪽으로 해볼게요

**Comment by gisellevonbingen** [comment]
관심가져주셔서 감사합니다
아카이브로 다운로드하는거 좋은 생각이네요
실제로 저도 관리할때는 압축파일로 관리하거든요

[설정] - [다운로드 설정] 쪽에 '압축파일로 다운로드' 이라는 설정을 추가하는 쪽으로 해볼게요
갤러리별 아카이브 파일 하나에 각 이미지를 계속해서 추가하는 식으로요

**Comment by gisellevonbingen** [comment]
https://github.com/gisellevonbingen/DoujinshiDownloader/releases/tag/1.00.06
이미지 다운로드시 압축파일에 모아서 다운로드하는 기능을 추가했습니다

말씀하시는 기능이 이게 맞나요?

**Comment by gisellevonbingen** [comment]
> 한장씩 받는 것 말고 리셈플된 아카이브를 다운로드하도록 설정할 수는 없나요?

아, 혹시 리샘플된 아카이브가 갤러리 오른쪽 'Download Archive' 에 있는
'Download Resampled Archive' 말씀인가요?
