### ISSUE TITLE
some corrections and questions

### ISSUE THREAD

**Issue by ghost** [gisellevonbingen/DoujinshiDownloader#17]
Some little grammar corrections:

1 - Open Downlaod Directory -> Open Downl**oad** Directory
2 - Confirm Before Cancel/Remvoe Download -> Confirm Before Cancel/Rem**ove** Download
3 - Downalod to Archive File (*.zip) -> Down**load** to Archive File (*.zip)
4 - Original (Not Convert) -> Original (**Don't** Convert) or Original (No **Conversion**)
5 - Supports Both Relative, Absolute Paths -> Supports Both Relative **and** Absolute Paths
6 - Some Directory Require Administrator Privileges -> Some Director**ies** Require Administrator Privileges
7 - Allow Notify Message -> Allow Notif**ications**
8 - When Main Form Hide -> When Main **Window Hidden** and Download Complete -> **On Download Completion**

Question: Is it possible to download the images at their original resolutions? I suppose not, right?

thanks for the program

**Comment by gisellevonbingen** [comment]
Oops, It's a series of terrible typos...
Tysm for your sharp eyes.

----
Q: Is it possible to download the images at their original resolutions? I suppose not, right?
A: Currently no, Let me think of a way.

**Comment by gisellevonbingen** [comment]
Typo fixed version is released.
Thank again.
https://github.com/gisellevonbingen/DoujinshiDownloader/releases/tag/01.02.00.03

**Comment by ghost** [comment]
> Oops, It's a series of terrible typos... Tysm for your sharp eyes.
> 
> Q: Is it possible to download the images at their original resolutions? I suppose not, right? A: Currently no, Let me think of a way.

I don't think it is possible at all, to be honest. e-hentai allows only a certain amount of bandwidth regarding the download of images on their original resolutions. unless there is a way to bypass that, I don't think it is possible for non-torrent scenarios. which is fine, they have the right to limit it.
