### ISSUE TITLE
Can you update the downloader?

### ISSUE THREAD

**Issue by warpath2012** [gisellevonbingen/DoujinshiDownloader#20]
Your program is very useful. i use it many years. But it can't download the image form exhentai website correctly now. can you update it? thanks a lot

**Comment by gisellevonbingen** [comment]
Hmm.. It was working fine until two weeks ago. I'll check.

**Comment by gisellevonbingen** [comment]
Fixed at e2534b36794ec041c784b52629d7eca535217bb4
And new version is available https://github.com/gisellevonbingen/DoujinshiDownloader/releases/tag/01.02.03.00
