### ISSUE TITLE
The remove button

### ISSUE THREAD

**Issue by Zhen-Bo** [gisellevonbingen/DoujinshiDownloader#5]
I suggest this downloader can add a button to remove all the complete mission instead click the remove button one by one
and add a check box,if it check you can remove from list without confirm message everytime
PS:Can't open this project on VS 2019 ;(

**Comment by Paverschlev** [comment]
Oh....Got it is in the cookie file

**Comment by gisellevonbingen** [comment]
I'm sorry to too late
that suggestion is very necessary feature

I'll two items below work as soon as possible
1. add a button 'Remove all the complete mission'
2. add a checkbox 'Remove a mission without messagebox'

Thank you for your interest

My workspace also VS2019.
i tried download repository as zip and open it, but problem did not occur
do you have any screenshot?

**Comment by Zhen-Bo** [comment]
![image](https://user-images.githubusercontent.com/30999421/68104103-a7229100-ff14-11e9-9b51-5292aa436206.png)
My friend said when he open the form GUI the DLL can't Instantiation like this
![image](https://user-images.githubusercontent.com/30999421/68104154-e7820f00-ff14-11e9-83c2-fc5765a676b1.png)

**Comment by gisellevonbingen** [comment]
Ah, all control not support form designer.
I dislike it.

so sorry

**Comment by Zhen-Bo** [comment]
Got it QAQ
