### ISSUE TITLE
Can download gif pic

### ISSUE THREAD

**Issue by Zhen-Bo** [gisellevonbingen/DoujinshiDownloader#7]
When I download a gif gallery the picture will not download successfully
Ex:The gif link is "https://bb.hitomi.la/images/a.gif" ,but the downloader will download "https://bb.hitomi.la/images/a.jpg"<- err 403
gallery:https://exhentai.org/g/1836951/4c546d573b/ (using hitomi download)
If using EXhentai download wont have this pronblem

**Comment by gisellevonbingen** [comment]
That problem is caused by wrong extension, when request to hitomi server
Hitomi server doesn't explain image file extension
So, I tested some galleries manually for wrote algoritm
That gallery is a new case, I haven't found

**Comment by gisellevonbingen** [comment]
![image](https://user-images.githubusercontent.com/44163945/107882729-75c5ad00-6f2e-11eb-890e-eadc7dc11d33.png)
Algorithm was fixed for download that gallery successfully
And, I testing if there are any problems with other cases
New version will release soon

Thank for bringing new issue
